apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secret
spec:
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-target-secret
    template:
      data:
        username: {{ .Values.secret.username }}
        password: {{ .Values.secret.password }}
