apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-file-share-secret
spec:
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-file-share-target-secret
    template:
      data:
        fileShare: {{ .Values.secret.fileShare }}
