apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClass }}
